In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()
a.T
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [3]:
a.shape
b = a.ravel()
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b[0,0] = 99
a
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 9
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
z = np.array([1, 2, 3])
z
z[:, np.newaxis]
z[np.newaxis, :]


array([[1, 2, 3]])

In [6]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape
a[0, 2, 1]
b = a.transpose(1, 2, 0)
b.shape
b[2, 1, 0]
b[2, 1, 0] = -1
a[0, 2, 1]

-1

In [7]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [8]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [9]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j
a[j]

array([1, 2, 3, 4])

In [10]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)